### ISSUE TITLE
Cannot read properties of undefined (reading 'seg')

### ISSUE THREAD

**Issue by tablatronix** [tablatronix/homebridge-simpler-wled#1]
```php
[9/24/2024, 8:57:31 PM] TypeError: Cannot read properties of undefined (reading 'seg')
    at WLEDAccessory.parseMessage (/homebridge/node_modules/homebridge-simpler-wled/src/wled-accessory.ts:255:36)
    at WebSocket.<anonymous> (/homebridge/node_modules/homebridge-simpler-wled/src/wled-accessory.ts:285:14)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/homebridge/node_modules/homebridge-simpler-wled/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/homebridge/node_modules/homebridge-simpler-wled/node_modules/ws/lib/receiver.js:596:14)
    at Receiver.getData (/homebridge/node_modules/homebridge-simpler-wled/node_modules/ws/lib/receiver.js:496:10)
    at Receiver.startLoop (/homebridge/node_modules/homebridge-simpler-wled/node_modules/ws/lib/receiver.js:167:16)
    at Receiver._write (/homebridge/node_modules/homebridge-simpler-wled/node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:564:12)
[9/24/2024, 8:57:31 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by tablatronix** [comment]
I fucking hate node, what a pile of shit, why does it crash so easily

**Comment by tablatronix** [comment]
When preset contains a segment
{"bri":255,"seg":{"col":[[168,92,255],[0,0,0],[0,0,0]],"fx":67,"sx":21,"ix":28,"pal":6}}
